-- ============================================================
-- ONLINE VOTING SYSTEM - DATABASE SCHEMA
-- PostgreSQL
--
-- Sensitive personal data is encrypted by PHP using AES-256-GCM.
-- *_hash columns are HMAC-SHA256 lookup values generated by PHP.
-- Passwords are stored using PHP password_hash().
-- ============================================================

-- ------------------------------------------------------------
-- 1. ELECTIONS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS elections (
    election_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    election_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CHECK (end_time > start_time)
);

-- ------------------------------------------------------------
-- 2. POSITIONS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS positions (
    position_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    position_name VARCHAR(100) NOT NULL UNIQUE
);

-- ------------------------------------------------------------
-- 3. POSITIONS BELONGING TO AN ELECTION
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS election_positions (
    election_position_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    election_id INTEGER NOT NULL
        REFERENCES elections(election_id) ON DELETE CASCADE,
    position_id INTEGER NOT NULL
        REFERENCES positions(position_id) ON DELETE RESTRICT,

    UNIQUE (election_id, position_id)
);

-- ------------------------------------------------------------
-- 4. USERS
--
-- member_id, first_name, last_name, email and phone are stored
-- encrypted by PHP. Hash columns are used only for lookup/
-- uniqueness because encrypted values cannot be searched directly.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    member_id_encrypted TEXT NOT NULL,
    member_id_hash CHAR(64) NOT NULL UNIQUE,

    first_name_encrypted TEXT NOT NULL,
    last_name_encrypted TEXT NOT NULL,

    email_encrypted TEXT NOT NULL,
    email_hash CHAR(64) NOT NULL UNIQUE,

    phone_encrypted TEXT,
    phone_hash CHAR(64),

    password_hash VARCHAR(255) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('pending', 'active', 'rejected')),

    role VARCHAR(20) NOT NULL DEFAULT 'voter'
        CHECK (role IN ('voter', 'superadmin')),

    terms_accepted BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- 5. CANDIDATES
--
-- A candidate is also a normal user/voter. A separate table is
-- used because candidate status is election/position specific.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS candidates (
    candidate_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL
        REFERENCES users(user_id) ON DELETE CASCADE,

    election_position_id INTEGER NOT NULL
        REFERENCES election_positions(election_position_id)
        ON DELETE CASCADE,

    application_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (application_status IN ('pending', 'approved', 'rejected')),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (user_id, election_position_id)
);

-- ------------------------------------------------------------
-- 6. VOTES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS votes (
    vote_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    election_position_id INTEGER NOT NULL
        REFERENCES election_positions(election_position_id)
        ON DELETE CASCADE,

    voter_id INTEGER NOT NULL
        REFERENCES users(user_id)
        ON DELETE CASCADE,

    candidate_id INTEGER NOT NULL
        REFERENCES candidates(candidate_id)
        ON DELETE CASCADE,

    voted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- One voter can vote once for each position in an election.
    UNIQUE (election_position_id, voter_id)
);

-- ------------------------------------------------------------
-- 7. INDEXES
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_elections_datetime
    ON elections(election_date, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_election_positions_election
    ON election_positions(election_id);

CREATE INDEX IF NOT EXISTS idx_candidates_position
    ON candidates(election_position_id);

CREATE INDEX IF NOT EXISTS idx_votes_position
    ON votes(election_position_id);